

name: 'ci/cd pipeline'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  compile:
    name: ''
    runs-on: ubuntu-latest
    environment: production

    
